version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: frother$123
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "shared_preload_libraries=pgvector"]
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
