version: '3.8'

name: OwnData 
services:
  postgres:
    build:
      context: ./postgres
      dockerfile: postgres.dockerfile
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/vector_extension.sql:/docker-entrypoint-initdb.d/0-vector_extension.sql

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=frother$123
      - POSTGRES_DB=OwnData
volumes:
  postgres_data: